# Homework 10

## Question 1

In [4]:
import numpy as np

Q1A = matrix(RDF, [[2,0,1],[0,2,2]])

show(Q1A)

show(LatexExpr("A = U \Sigma V^T"))
show(Q1A.SVD())

[2.0 0.0 1.0]
[0.0 2.0 2.0]

A = U \Sigma V^T

(
                                                            [    0.29814239699997214      0.8944271909999157    -0.33333333333333337]
[  0.4472135954999581   0.8944271909999156]  [3.0 0.0 0.0]  [     0.5962847939999439    -0.44721359549995815     -0.6666666666666666]
[  0.8944271909999159 -0.44721359549995815], [0.0 2.0 0.0], [     0.7453559924999298 -1.1102230246251565e-16      0.6666666666666667]
)

In [8]:
## Producing Sigma
Q1ATA = Q1A.transpose() * Q1A
Q1ATA = Q1ATA.change_ring(QQ)

show(LatexExpr("A^{T}A ="), Q1ATA)

show(LatexExpr("\lambda_1, \lambda_2, \lambda_n ="), Q1ATA.eigenvalues())
show(Q1ATA.characteristic_polynomial()(x=l))

Q1Sigma = diagonal_matrix(QQ, [sqrt(x) for x in Q1ATA.eigenvalues()])
Q1Sigma = Q1Sigma[0:Q1A.nrows(),0:Q1A.ncols()]

show(LatexExpr("\Sigma ="), Q1Sigma)

A^{T}A = [4 0 2]
[0 4 4]
[2 4 5]

\lambda_1, \lambda_2, \lambda_n = [9, 4, 0]

l^3 - 13*l^2 + 36*l

\Sigma = [3 0 0]
[0 2 0]

In [7]:
## Producing V
def eigenvalue_matrix(ATA):
    var('l', latex_name=r'\lambda')
    eig_Matrix = ATA - diagonal_matrix(ATA.diagonal())
    eig_Matrix += diagonal_matrix([x - l for x in ATA.diagonal()])
    
    return eig_Matrix

show(eigenvalue_matrix(Q1ATA))

def SVD_V(ATA, eig_matrix):
    var('l', latex_name=r'\lambda')
    vs = []
    for e in ATA.eigenvalues():
        show(LatexExpr("\lambda="), e)
        show(eig_matrix(l=e), LatexExpr("\underrightarrow{RREF}"), eig_matrix(l=e).rref())
        null_space = eig_matrix(l=e).right_kernel_matrix()
        factor = 1/sqrt(sum([(x)^2 for x in null_space.list()]))
        show(LatexExpr("\overrightarrow{v}="), factor, null_space.transpose(), LatexExpr("="), factor * null_space.transpose())
        vs.append(factor * null_space)
    show([x.transpose() for x in vs])
    V = matrix(CC, [x.list() for x in vs])
    return V

Q1V = SVD_V(Q1ATA, eigenvalue_matrix(Q1ATA)).transpose()
show(LatexExpr("V="),Q1V)
show(LatexExpr("V^T="),Q1V.transpose())

[-l + 4      0      2]
[     0 -l + 4      4]
[     2      4 -l + 5]

\lambda= 9

[-5  0  2]
[ 0 -5  4]
[ 2  4 -4] \underrightarrow{RREF} [   1    0 -2/5]
[   0    1 -4/5]
[   0    0    0]

\overrightarrow{v}= 2/15*sqrt(5) [  1]
[  2]
[5/2] = [2/15*sqrt(5)]
[4/15*sqrt(5)]
[ 1/3*sqrt(5)]

\lambda= 4

[0 0 2]
[0 0 4]
[2 4 1] \underrightarrow{RREF} [1 2 0]
[0 0 1]
[0 0 0]

\overrightarrow{v}= 2/5*sqrt(5) [   1]
[-1/2]
[   0] = [ 2/5*sqrt(5)]
[-1/5*sqrt(5)]
[           0]

\lambda= 0

[4 0 2]
[0 4 4]
[2 4 5] \underrightarrow{RREF} [  1   0 1/2]
[  0   1   1]
[  0   0   0]

\overrightarrow{v}= 1/3 [ 1]
[ 2]
[-2] = [ 1/3]
[ 2/3]
[-2/3]

[
[2/15*sqrt(5)]  [ 2/5*sqrt(5)]  [ 1/3]
[4/15*sqrt(5)]  [-1/5*sqrt(5)]  [ 2/3]
[ 1/3*sqrt(5)], [           0], [-2/3]
]

V= [ 0.298142396999972  0.894427190999916  0.333333333333333]
[ 0.596284793999944 -0.447213595499958  0.666666666666667]
[ 0.745355992499930  0.000000000000000 -0.666666666666667]

V^T= [ 0.298142396999972  0.596284793999944  0.745355992499930]
[ 0.894427190999916 -0.447213595499958  0.000000000000000]
[ 0.333333333333333  0.666666666666667 -0.666666666666667]

In [ ]:
Q1AAT = Q1A * Q1A.transpose()
Q1AAT = Q1AAT.change_ring(QQ)

show(Q1AAT)
show(Q1AAT.characteristic_polynomial())

def SVD_U_full(AAT, eig_matrix):
    var('l', latex_name=r'\lambda')
    vs = []
    for e in AAT.eigenvalues():
        show(LatexExpr("\lambda="), e)
        show(eig_matrix(l=e), LatexExpr("\underrightarrow{RREF}"), eig_matrix(l=e).rref())
        null_space = eig_matrix(l=e).right_kernel_matrix()
        factor = 1/sqrt(sum([(x)^2 for x in null_space.list()]))
        show(LatexExpr("\overrightarrow{u}="), factor, null_space.transpose(), LatexExpr("="), factor * null_space.transpose())
        vs.append(factor * null_space)
    show([x.transpose() for x in vs])
    V = matrix(CC, [x.list() for x in vs])
    return V

Q1U = SVD_U_full(Q1AAT, eigenvalue_matrix(Q1AAT))
show(LatexExpr("U="),Q1U)

In [ ]:
show(Q1U * Q1Sigma.change_ring(CC) * Q1V.transpose())

In [ ]:
Q1t1 = matrix([[1/sqrt(5), 2*sqrt(5)/5], [2/sqrt(5), -sqrt(5)/5]])
Q1t2 = matrix([[3,0,0],[0,2,0]])
Q1t3 = matrix([[2*sqrt(5)/15, 4*sqrt(5)/15, sqrt(5)/3],[2*sqrt(5)/5, -sqrt(5)/5, 0],[1/3, 2/3, -2/3]])
show(Q1t3.change_ring(CC))
show(Q1V.transpose())
show(Q1t1 * Q1t2 * Q1t3)

## Question 2

In [322]:
Q2A = matrix(RDF, [[3,2],[2,3],[2,-2]])

show(Q2A)

show(LatexExpr("A = U \Sigma V^T"))
show(Q2A.SVD())

[ 3.0  2.0]
[ 2.0  3.0]
[ 2.0 -2.0]

A = U \Sigma V^T

(
[    -0.7071067811865477      0.2357022603955157     -0.6666666666666666]
[    -0.7071067811865475    -0.23570226039551587      0.6666666666666666]
[-1.6653345369377348e-16      0.9428090415820632     0.33333333333333326],

[4.999999999999999               0.0]
[              0.0               3.0]
[              0.0               0.0],

[-0.7071067811865477  0.7071067811865474]
[-0.7071067811865474 -0.7071067811865477]
)

In [407]:
Q2ATA = Q2A.transpose() * Q2A
Q2ATA = Q2ATA.change_ring(QQ)

show(LatexExpr("A^{T}A ="), Q2ATA)
show(Q2ATA.characteristic_polynomial()(x=l))

show(LatexExpr("\lambda_1, \lambda_2, \lambda_n ="), Q2ATA.eigenvalues())

Q2Sigma = diagonal_matrix(QQ, [sqrt(x) for x in Q2ATA.eigenvalues()])
Q2SigmaFull = Q2Sigma[0:Q2A.nrows(),0:Q2A.ncols()]

show(LatexExpr("\Sigma ="), Q2Sigma)

A^{T}A = [17  8]
[ 8 17]

l^2 - 34*l + 225

\lambda_1, \lambda_2, \lambda_n = [25, 9]

\Sigma = [5 0]
[0 3]

In [340]:
show(eigenvalue_matrix(Q2ATA))

Q2V = SVD_V(Q2ATA, eigenvalue_matrix(Q2ATA)).transpose()
show(LatexExpr("V="),Q2V)

[-l + 17       8]
[      8 -l + 17]

\lambda= 25

[-8  8]
[ 8 -8] \underrightarrow{RREF} [ 1 -1]
[ 0  0]

\overrightarrow{v}= 1/2*sqrt(2) [1]
[1] = [1/2*sqrt(2)]
[1/2*sqrt(2)]

\lambda= 9

[8 8]
[8 8] \underrightarrow{RREF} [1 1]
[0 0]

\overrightarrow{v}= 1/2*sqrt(2) [ 1]
[-1] = [ 1/2*sqrt(2)]
[-1/2*sqrt(2)]

[
[1/2*sqrt(2)]  [ 1/2*sqrt(2)]
[1/2*sqrt(2)], [-1/2*sqrt(2)]
]

V= [ 0.707106781186547  0.707106781186547]
[ 0.707106781186547 -0.707106781186547]

In [411]:
Q2AAT = Q2A * Q2A.transpose()
Q2AAT = Q2AAT.change_ring(QQ)

show(Q2AAT)
show(Q2AAT.characteristic_polynomial())

def SVD_U_reduced(AAT, eig_matrix):
    var('l', latex_name=r'\lambda')
    vs = []
    e = AAT.eigenvalues()
    show(LatexExpr("\lambda="), e[0])
    u_1 = (1/sqrt(e[0])) * Q2A * Q2V[:,0]
    show(1/sqrt(e[0]), Q2A, Q2V[:,0], LatexExpr("="), u_1)
    vs.append(u_1.transpose())
    
    show(LatexExpr("\lambda="), e[1])
    show(eig_matrix(l=e[1]), LatexExpr("\underrightarrow{RREF}"), eig_matrix(l=e[1]).rref())
    null_space = eig_matrix(l=e[1]).right_kernel_matrix()
    factor = 1/sqrt(sum([(x)^2 for x in null_space.list()]))
    show(LatexExpr("\overrightarrow{u}="), factor, null_space.transpose(), LatexExpr("="), factor * null_space.transpose())
    vs.append(factor * null_space)
    show([x.transpose() for x in vs])
    V = matrix(CC, [vector(x.transpose()) for x in vs]).transpose()
    return V

Q2U = SVD_U_reduced(Q2AAT, eigenvalue_matrix(Q2AAT))
show(LatexExpr("U="),Q2U)

[13 12  2]
[12 13 -2]
[ 2 -2  8]

x^3 - 34*x^2 + 225*x

\lambda= 25

1/5 [ 3.0  2.0]
[ 2.0  3.0]
[ 2.0 -2.0] [0.707106781186547]
[0.707106781186547] = [0.707106781186548]
[0.707106781186548]
[0.000000000000000]

\lambda= 9

[ 4 12  2]
[12  4 -2]
[ 2 -2 -1] \underrightarrow{RREF} [   1    0 -1/4]
[   0    1  1/4]
[   0    0    0]

\overrightarrow{u}= 1/6*sqrt(2) [ 1]
[-1]
[ 4] = [ 1/6*sqrt(2)]
[-1/6*sqrt(2)]
[ 2/3*sqrt(2)]

[
[0.707106781186548]  [ 1/6*sqrt(2)]
[0.707106781186548]  [-1/6*sqrt(2)]
[0.000000000000000], [ 2/3*sqrt(2)]
]

U= [ 0.707106781186548  0.235702260395516]
[ 0.707106781186548 -0.235702260395516]
[ 0.000000000000000  0.942809041582063]

In [409]:
show(Q2U * Q2SigmaFull.change_ring(CC) * Q2V.transpose())

[ 3.00000000000000  2.00000000000000]
[ 2.00000000000000  3.00000000000000]
[ 2.00000000000000 -2.00000000000000]

In [438]:
show(matrix([[sqrt(2)/2,sqrt(2)/6], [sqrt(2)/2,-sqrt(2)/6],[0,(2*sqrt(2))/3]])*matrix([[5,0],[0,3]])*matrix([[sqrt(2)/2,sqrt(2)/2],[sqrt(2)/2,-sqrt(2)/2]]))

[ 3  2]
[ 2  3]
[ 2 -2]

## Question 3

In [419]:
var('a,b,c,d,e,f,g,h,i,j')
Q3A = matrix([[a,b],[c,d]])
Q3B = matrix([[e,f,g],[h,i,j]])
show(Q3A * Q3B)

[a*e + b*h a*f + b*i a*g + b*j]
[c*e + d*h c*f + d*i c*g + d*j]