# Homework 11

## Question 1 a

In [52]:
Q1A = matrix([[-1, 2],[3,-4]])

show(Q1A)

[-1  2]
[ 3 -4]

### 1-norm

In [53]:
show(LatexExpr("norm_1="), Q1A.norm(1))

norm_1= 6.0

### $\infty$-norm

In [54]:
show(LatexExpr("norm_\infty="), Q1A.norm(Infinity))

norm_\infty= 7.0

### Frobenius-norm

In [55]:
show(LatexExpr("norm_{Frob     enius}="), Q1A.norm('frob'))
show(sqrt(30), LatexExpr("="), N(sqrt(30)))

norm_{Frob     enius}= 5.477225575051661

sqrt(30) = 5.47722557505166

### Condition Number

In [56]:
show(LatexExpr("cond_1(A)="), 6 * (7/2), LatexExpr("="), Q1A.change_ring(RDF).condition(p=1))

cond_1(A)= 21 = 20.999999999999993

## Question 1 b

In [57]:
Q2B = matrix([[1,2],[2,4]])

show(Q2B)

[1 2]
[2 4]

### 1-norm

In [58]:
show(LatexExpr("norm_1="), Q2B.norm(1))

norm_1= 6.0

### $\infty$-norm

In [59]:
show(LatexExpr("norm_\infty="), Q2B.norm(Infinity))

norm_\infty= 6.0

### Frobenius-norm

In [60]:
show(LatexExpr("norm_{Frobenius}="), Q2B.norm('frob'))

norm_{Frobenius}= 5.0

### Condition Number

In [ ]:
show(LatexExpr("cond_1(A)="), Q2B.change_ring(RDF).condition(p=1))

## Question 1 c

In [64]:
Q2C = matrix(([5,0,0],[0,10,0],[0,0,20]))

show(Q2C)

[ 5  0  0]
[ 0 10  0]
[ 0  0 20]

### 1-norm

In [65]:
show(LatexExpr("norm_1="), Q2C.norm(1))

norm_1= 20.0

### $\infty$-norm

In [68]:
show(LatexExpr("norm_\infty="), Q2C.norm(Infinity))

norm_\infty= 20.0

### Frobenius-norm

In [70]:
show(LatexExpr("norm_{Frobenius}="), Q2C.norm('frob'))

norm_{Frobenius}= 22.9128784747792

In [27]:
import numpy as np

A = np.zeros((3,3))

print (A)

points_skewed = np.array([[0,   0, 50, 50],
                              [0, 100, 75, 25]])

a = points_skewed[:,0].reshape((1,2))

print (a)

a = np.append(a, [1])

print(a)

A[0,:] += a

print (np.zeros((3,3)) + (A[0,:] + a))

H = A[:,:]

print (H)

A = np.zeros((3,3))

A[1,:] += a

print(A)

H = np.hstack((H, A))

A = np.zeros((3,3))

A[2,:] += a

H = np.hstack((H,A))

print(H)

V = np.vstack((H))

V = np.vstack((V, V))

print(V)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0]]
[0 0 1]
[[0. 0. 2.]
 [0. 0. 2.]
 [0. 0. 2.]]
[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
